--Create database Learning;
--use Learning;

Select * from dbo.Customer;
select * from dbo.Transactions;
select * from dbo.prod_cat_info;

--#What is the total no of rows in each 3 tables in databases;
SELECT (SELECT COUNT(*) FROM Customer) AS CustCnt,
       (SELECT COUNT(*) FROM Transactions) AS TransCnt,     
       (SELECT COUNT(*) FROM prod_cat_info) AS ProdCnt

--# what is the total number of transactions that have a return ? 
SELECT COUNT(total_amt) FROM Transactions
WHERE total_amt LIKE '-%'


--# As you would have noticed, the dates provided across the datasets are not in a correct format. As first steps, pls convert the date variables into valid date formats before proceeding ahead.

SELECT CONVERT(DATE, DOB, 105) AS DATES FROM Customer;
SELECT CONVERT(DATE, tran_date, 105) FROM Transactions;

--# What is the time range of the transaction data available for analysis? Show the output in number of days, months and years simultaneously in different columns.
SELECT DATEDIFF(DAY, MIN(CONVERT(DATE, tran_date, 105)), MAX(CONVERT(DATE, tran_date, 105))), 
DATEDIFF(MONTH, MIN(CONVERT(DATE, tran_date, 105)), MAX(CONVERT(DATE, tran_date, 105))),  
DATEDIFF(YEAR, MIN(CONVERT(DATE, tran_date, 105)), MAX(CONVERT(DATE, tran_date, 105))) 
FROM Transactions;


--# Which product category does the sub-category "DIY" belong to?
SELECT prod_cat FROM prod_cat_info
WHERE prod_subcat LIKE 'DIY'

--#--DATA ANALYSIS
--1.	Which channel is most frequently used for transactions?
SELECT Store_type, COUNT(TRANSACTION_ID) TransCnt
FROM Transactions
GROUP BY Store_type
ORDER BY COUNT(TRANSACTION_ID) DESC
--Ans.(e-Shop)

--2. What is the count of Male and Female customers in the database?

SELECT Gender, COUNT(CUSTOMER_ID) AS CustCnt
FROM Customer
WHERE Gender IN ('M' , 'F')
GROUP BY Gender
--Ans. Male = 2892, Female = 2753

--# 3.	From which city do we have the maximum number of customers and how many?

SELECT Top 1
city_code, COUNT(CUSTOMER_ID) CustCnt
FROM Customer
GROUP BY city_code
ORDER BY CustCnt DESC

--Ans. 595 Customer from city_code 3

--# 4.	How many sub-categories are there under the Books category?

SELECT COUNT(prod_subcat) AS SubCat_Cnt
FROM prod_cat_info
WHERE prod_cat = 'BOOKS'
GROUP BY prod_cat
--Ans. 6

--#5.	What is the maximum quantity of products ever ordered?

SELECT  Qty
FROM Transactions
ORDER BY Qty DESC
--Ans. 5

--6.	What is the net total revenue generated in categories Electronics and Books?

ALTER table prod_cat_info
ALTER column prod_cat_code int NOT NULL

alter table dbo.Transactions
alter column prod_cat_code int NOT NULL 
select * from dbo.Transactions;

-- Alter table transactions with column total amount from varchar to int for calculation

alter table Transactions alter column total_amt float;


SELECT SUM(total_amt) Amount
FROM Transactions
INNER JOIN prod_cat_info
on prod_cat_info.prod_cat_code = Transactions.prod_cat_code
WHERE prod_cat IN ('Books' , 'Electronics')



--7.	How many customers have >10 transactions with us, excluding returns?

SELECT COUNT(customer_id) AS CUSTOMER_COUNT
FROM Customer WHERE customer_id IN 
(
SELECT customer_id
FROM Transactions
LEFT JOIN Customer ON customer_id = cust_id
WHERE TOTAL_AMT NOT LIKE '-%'
GROUP BY
customer_id
HAVING 
COUNT(transaction_id) > 10
)
--Ans. 6 Customers

--# 8.	What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?

SELECT SUM(TOTAL_AMT) AS AMOUNT FROM Transactions
INNER JOIN prod_cat_info ON prod_cat = prod_cat
	  AND prod_subcat = prod_sub_cat_code
WHERE PROD_CAT IN ('CLOTHING','ELECTRONICS') AND STORE_TYPE = 'FLAGSHIP STORE'

--# 9.	What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.
SELECT prod_subcat_code, SUM(TOTAL_AMT) REVENUE
FROM Transactions
LEFT JOIN Customer ON CUST_ID=CUSTOMER_ID
LEFT JOIN prod_cat_info ON prod_sub_cat_code = PROD_SUBCAT_CODE 
WHERE  prod_subcat_code = '3' AND GENDER = 'M'
GROUP BY PROD_SUBCAT_CODE, PROD_SUBCAT




--# 10.	What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
SELECT TOP 5 
prod_subcat_code, (SUM(TOTAL_AMT)/(SELECT SUM(TOTAL_AMT) FROM Transactions))*100 AS PERCANTAGE_OF_SALES, 
(COUNT(CASE WHEN QTY< 0 THEN QTY ELSE NULL END)/SUM(QTY))*100 AS PERCENTAGE_OF_RETURN
FROM Transactions
INNER JOIN prod_cat_info ON prod_sub_cat_code = prod_subcat_code 
GROUP BY prod_sub_cat_code
ORDER BY SUM(TOTAL_AMT) DESC



--# 11.	For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days of transactions from max transaction date available in the data?

SELECT CUST_ID, SUM(TOTAL_AMT) AS REVENUE FROM Transactions
WHERE CUST_ID IN (SELECT CUSTOMER_ID FROM Customer
WHERE DATEDIFF(YEAR,CONVERT(DATE,DOB,103), GETDATE()) BETWEEN 25 AND 35)
AND CONVERT(DATE,tran_date,103) BETWEEN DATEADD(DAY, -30,(SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions))
AND (SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions)
GROUP BY cust_id


--# 12.	Which product category has seen the max value of returns in the last 3 months of transactions?

SELECT TOP 1 prod_cat, SUM(TOTAL_AMT) FROM Transactions 
INNER JOIN prod_cat_info ON prod_subcat_code = prod_subcat
WHERE total_amt < 0 AND
CONVERT(date, tran_date,103) BETWEEN DATEADD(MONTH,-3,(SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions))
AND (SELECT MAX(CONVERT (DATE,TRAN_DATE, 103)) FROM Transactions)
GROUP BY prod_cat
ORDER BY 2 DESC


--# 13.	Which store-type sells the maximum products; by value of sales amount and by quantity sold?

-- Alter table transactions with column Qty from varchar to int for calculation

alter table Transactions alter column Qty int;
alter table Transactions alter column prod_cat_code int not null;

SELECT Store_type, SUM(total_amt) tot_sales, SUM(Qty) tot_quant from Transactions
group  by Store_type
Having SUM(total_amt) >= ALL (select SUM(total_amt) from Transactions group by Store_type)
AND SUM(Qty) >= ALL (select SUM(Qty) from Transactions group by Store_type)
 

--# 14.	What are the categories for which average revenue is above the overall average.

select prod_subcat_code, AVG(total_amt) as average from Transactions
inner join prod_cat_info on prod_subcat_code=prod_sub_cat_code
group by prod_subcat_code
having AVG(total_amt)> (select AVG(total_amt) from Transactions)

--# 15.	Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.

select prod_cat, prod_subcat_code, AVG(total_amt) as Average_rev, SUM(total_amt) as Revenue from Transactions
inner join prod_cat_info on prod_sub_cat_code=prod_subcat_code
where prod_cat IN
(select top 5 prod_cat from Transactions
inner join prod_cat_info on prod_sub_cat_code=prod_subcat_code
group by prod_cat
order by SUM(Qty) DESC)
group by prod_cat, prod_subcat_code

